name: DynSpinner
author: fcartegnie
category: Effects
current: 1.0
tags: [element, spinner, ajax, svg, canvas]
demo: http://fcartegnie.github.com/DynSpinner/
docs: http://github.com/fcartegnie/DynSpinner/blob/master/Docs/DynSpinner.md 

